export const MATCHES_TOTAL_STORAGE = "MATCHES_TOTAL";
export const MATCHES_WON_STORAGE = "MATCHES_WON";
export const MATCHES_CREATED_STORAGE = "MATCHES_CREATED";
export const AUTH_TOKEN_STORAGE = "AUTH_TOKEN";
export const PREV_SCREEN_STORAGE = "PREV_SCREEN";